name: BungeeServerName
version: 1.0
author: Datatags
main: me.datatags.bungeeservername.BungeeServerName
api-version: 1.16
depend: [PlaceholderAPI]
commands:
    servername:
        description: Gets the server name
        permission: bungeeservername.get
    updateservername:
        description: Updates the server name immediately if possible
        permission: bungeeservername.update
permissions:
    bungeeservername.get:
        description: Permission to display the server name
    bungeeservername.update:
        description: Permission to immediately update the server name
